In [5]:
import sys
import os
path=os.path.abspath(os.getcwd())
sys.path.insert(1, path+"/../manager")
sys.path.insert(1, path+"/../strategy")
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import extractor as ext
import datetime as datetime
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
def load_data(assets,start,end,path):
    data = {}
    for asset in assets :
        data[asset] = extractor.extract_data(asset,start,end,["Price"],"../collector/"+path)["Price"]
    return pd.DataFrame(data)

In [60]:
assets = ["BTC","ETH","BNB","XRP","ADA","LTC","SOL","UNI","AAVE","LINK","MKR","FTM","EOS","SAND","XTZ","TRX"]

extractor=ext.Extractor()
path="binance_1h"
start=datetime.datetime(2023, 1, 2 ,0, 0, 0, 0) 
end=datetime.datetime(2023, 3, 2 ,0, 0, 0, 0)
data = load_data(assets,start,end,path)

In [61]:
data

BTC      ETH    BNB     XRP     ADA    LTC    SOL  \
2023-01-02 00:00:00  16602.12  1201.03  244.8  0.3386  0.2491  70.82   9.97   
2023-01-02 01:00:00  16616.75  1200.34  244.4  0.3387  0.2499  70.91   9.99   
2023-01-02 02:00:00  16588.35  1198.16  243.6  0.3366  0.2488  70.40   9.91   
2023-01-02 03:00:00  16565.04  1195.16  242.1  0.3253  0.2476  70.14   9.85   
2023-01-02 04:00:00  16587.85  1196.79  242.4  0.3266  0.2482  70.52   9.92   
...                       ...      ...    ...     ...     ...    ...    ...   
2023-03-01 20:00:00  23690.88  1655.01  302.3  0.3831  0.3605  97.17  22.42   
2023-03-01 21:00:00  23355.14  1634.79  300.9  0.3805  0.3566  96.65  22.15   
2023-03-01 22:00:00  23421.23  1642.54  301.6  0.3833  0.3583  97.26  22.25   
2023-03-01 23:00:00  23553.73  1657.01  302.3  0.3828  0.3592  97.51  22.45   
2023-03-02 00:00:00  23531.94  1656.53  302.0  0.3833  0.3588  97.40  22.41   

                       UNI  AAVE   LINK    MKR     FTM    EOS    SAND    XTZ  \
2023-01-02 00:00:00  5.254  52.0  5.616  512.0  0.2007  0.880  0.3881  0.718   
2023-01-02 01:00:00  5.248  52.2  5.628  514.0  0.2008  0.879  0.3884  0.719   
2023-01-02 02:00:00  5.221  51.7  5.606  511.0  0.2003  0.876  0.3853  0.715   
2023-01-02 03:00:00  5.203  51.6  5.563  508.0  0.1989  0.871  0.3817  0.710   
2023-01-02 04:00:00  5.198  51.8  5.580  509.0  0.1992  0.873  0.3844  0.715   
...                    ...   ...    ...    ...     ...    ...     ...    ...   
2023-03-01 20:00:00  6.782  81.7  7.435  932.0  0.4597  1.192  0.6977  1.193   
2023-03-01 21:00:00  6.703  80.9  7.357  932.0  0.4550  1.189  0.6914  1.176   
2023-03-01 22:00:00  6.753  81.7  7.434  936.0  0.4598  1.199  0.6948  1.185   
2023-03-01 23:00:00  6.805  82.4  7.512  942.0  0.4664  1.205  0.6995  1.190   
2023-03-02 00:00:00  6.821  82.2  7.483  940.0  0.4661  1.202  0.7009  1.188   

                         TRX  
2023-01-02 00:00:00  0.05485  
2023-01-02 01:00:00  0.05481  
2023-01-02 02:00:00  0.05483  
2023-01-02 03:00:00  0.05450  
2023-01-02 04:00:00  0.05455  
...                      ...  
2023-03-01 20:00:00  0.07016  
2023-03-01 21:00:00  0.06975  
2023-03-01 22:00:00  0.06984  
2023-03-01 23:00:00  0.06972  
2023-03-02 00:00:00  0.06960  

[1417 rows x 16 columns]

In [62]:
# Set up the data
x_array = np.array(data)

n = x_array.shape[1]

# Compute the logarithmic returns
log_returns = np.diff(np.log(x_array),axis=0)

In [71]:
# Compute the expected values vector
mu = np.mean(log_returns,axis=0)

# Compute the covariance matrix
Sigma = np.cov(log_returns.T)

print("The Expected Value vector\n\n",mu)
print("\n")
print("First 7 rows & columns of the Covariance Matrix\n\n",np.round(Sigma[:7,:7],7))

The Expected Value vector

 [2.46347634e-04 2.27080177e-04 1.48294821e-04 8.75695640e-05
 2.57705302e-04 2.25059862e-04 5.71982135e-04 1.84333614e-04
 3.23383887e-04 2.02693584e-04 4.29064442e-04 5.95048692e-04
 2.20212011e-04 4.17445046e-04 3.55619301e-04 1.68193772e-04]


First 7 rows & columns of the Covariance Matrix

 [[2.390e-05 2.480e-05 1.910e-05 1.830e-05 2.540e-05 2.210e-05 3.730e-05]
 [2.480e-05 3.160e-05 2.340e-05 2.250e-05 3.120e-05 2.700e-05 4.670e-05]
 [1.910e-05 2.340e-05 2.920e-05 2.030e-05 2.970e-05 2.450e-05 4.050e-05]
 [1.830e-05 2.250e-05 2.030e-05 3.780e-05 2.960e-05 2.370e-05 4.080e-05]
 [2.540e-05 3.120e-05 2.970e-05 2.960e-05 6.140e-05 3.470e-05 5.960e-05]
 [2.210e-05 2.700e-05 2.450e-05 2.370e-05 3.470e-05 4.740e-05 5.020e-05]
 [3.730e-05 4.670e-05 4.050e-05 4.080e-05 5.960e-05 5.020e-05 1.403e-04]]


In [64]:
def mean_variance(mu: np.ndarray, sigma_inv: np.ndarray) -> np.ndarray:
    """
    Calculates the optimal portfolio weights for mean-variance optimization.

    Parameters:
    - mu (np.ndarray): Expected returns of individual assets.
    - sigma_inv (np.ndarray): Inverse of the covariance matrix of asset returns.

    Returns:
    - np.ndarray: Optimal portfolio weights that minimize portfolio variance for a given level of expected return.
    """

    # Calculate the portfolio weights using mean-variance optimization formula
    w0 = np.dot(sigma_inv, mu)

    # Normalize the weights to ensure they sum up to 1
    return w0 / np.matmul(np.abs(w0.T), np.ones(len(w0)))

In [69]:
# Compute the weights of the optimal portfolio
w = mean_variance(mu,np.linalg.inv(Sigma))

print("Standard Mean Variance Optimal Portfolio\n\n",np.round(w,4))

Standard Mean Variance Optimal Portfolio

 [ 0.2802 -0.0923 -0.0895 -0.104   0.0079  0.0041  0.0616 -0.1138  0.0074
 -0.042   0.0826  0.0367  0.0088  0.0077  0.0465  0.015 ]


In [66]:
import cvxpy as cvx
def long_only_mean_variance(Sigma: np.ndarray, mu: np.ndarray, risk_tolerance: float) -> np.ndarray:
    """
    Markowitz Long Only optimal portfolio.

    Parameters:
    - Sigma (np.ndarray): Covariance matrix of asset returns.
    - mu (np.ndarray): Expected returns of individual assets.
    - riskTolerance (float): Risk tolerance parameter for the mean-variance optimization.

    Returns:
    - np.ndarray: Optimal long-only portfolio weights based on mean-variance optimization.
    """

    # Total number of assets
    n = len(mu)

    # Variable vector of length n for optimization
    z = cvx.Variable(n)

    # The expected value for a portfolio of weights w
    ret = mu @ z

    # The variance for a portfolio of weights w
    risk = cvx.quad_form((w + z), Sigma)

    # The objective function to minimize
    objective = cvx.Minimize(risk - risk_tolerance * ret)

    # The (linear) constraints
    constraints = [np.ones((1, n)) @ (w + z) <= 1, (w + z) >= 0]

    # Optimization problem
    prob = cvx.Problem(objective, constraints)

    # Solve the optimization problem
    prob.solve(verbose=False)

    # Return the updated portfolio weights
    return w + np.asarray(z.value)

In [68]:
# Investor's risk tolerance
risk_tolerance = 0.1

# Compute the weights of the optimal portfolio
w = long_only_mean_variance(Sigma,mu,risk_tolerance)

print("Long Only Mean Variance Optimal Portfolio\n\n",np.round(w,4))

Long Only Mean Variance Optimal Portfolio

 [ 0.2209 -0.     -0.     -0.     -0.     -0.      0.0694 -0.     -0.
 -0.      0.1074  0.0282 -0.     -0.      0.0315 -0.    ]
